### PR TITLE
Adding checks to sample to see if NFC is available on the device

### PR DESCRIPTION
**Pull request by JamieFarrelly**
Making NFCUtils a bit more useful by allowing you to call a method to see if NFC is available on the device, and then another method to see if NFC is actually enabled on the device. This way you can easily tell apart a device that doesn't have NFC between a device that does have NFC but it's just turned off.

Updated the sample app to also use this to display a more informative message. Hopefully the French translation makes sense, had to use Google Translate!

### CODE REVIEW

**Comment by devnied** [comment]
Hi, Thanks for your PR.
Can you replace the french translation with "Votre appareil n'est pas compatible NFC. Cela est nécessaire pour le fonctionnement de l\'application."

**Comment by JamieFarrelly** [comment]
Sure, I had a feeling the Google Translate translation wouldn't be the best.

**Comment by devnied** [comment]
Thanks

**Comment by SHOUHUJIAJIA** [comment]
translate_24dp

**Pull request merged**
